/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";

import { useControls } from "leva";
import * as THREE from "three";
import { VISEMES } from "wawa-lipsync";
import { lipsyncManager } from "../App";

let setupMode = false;

// Co-articulation blend table: when a vowel is active, nearby vowels retain
// a small partial shape. This simulates how the mouth continuously transitions
// between phonemes rather than jumping between discrete positions.
const VOWEL_BLENDS = {
  [VISEMES.aa]: { [VISEMES.E]: 0.25, [VISEMES.O]: 0.2 },
  [VISEMES.E]:  { [VISEMES.aa]: 0.25, [VISEMES.I]: 0.2 },
  [VISEMES.I]:  { [VISEMES.E]: 0.2,  [VISEMES.U]: 0.15 },
  [VISEMES.O]:  { [VISEMES.aa]: 0.2, [VISEMES.U]: 0.25 },
  [VISEMES.U]:  { [VISEMES.O]: 0.25, [VISEMES.I]: 0.15 },
};

export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF(
    "/models/64f1a714fe61576b46f27ca2.glb"
  );

  const { smoothMovements, mouthIntensity } = useControls("Avatar", {
    smoothMovements: {
      value: true,
      label: "Smooth Movements",
    },
    mouthIntensity: {
      value: 0.7,
      min: 0.3,
      max: 1.0,
      step: 0.05,
      label: "Mouth Intensity",
    },
  });

  const { animations } = useGLTF("/models/animations.glb");

  const group = useRef();
  const { actions, mixer } = useAnimations(animations, group);
  const [animation, setAnimation] = useState(
    animations.find((a) => a.name === "Idle") ? "Idle" : animations[0].name // Check if Idle animation exists otherwise use first animation
  );
  useEffect(() => {
    actions[animation]
      ?.reset()
      .fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5)
      .play();
    return () => actions[animation]?.fadeOut(0.5);
  }, [animation]);

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {}
        }
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);

  useFrame(() => {
    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    // LIPSYNC
    if (setupMode) {
      return;
    }

    const viseme = lipsyncManager.viseme;
    const state = lipsyncManager.state;

    // Volume-scaled intensity: mouth opens proportionally to how loud the
    // speaker is rather than always snapping to 100% open.
    // Apply user-controlled intensity multiplier to fine-tune mouth opening.
    const intensity = lipsyncManager.getIntensity() * mouthIntensity;

    // Lerp speeds tuned per phoneme category.
    // Vowels move slowly (natural formant glides), consonants faster (sharp
    // bursts), but still much slower than the original to avoid jitter.
    const isVowel = state === "vowel";
    const activeLerpSpeed   = smoothMovements ? (isVowel ? 0.06 : 0.14) : 0.5;
    const inactiveLerpSpeed = smoothMovements ? (isVowel ? 0.04 : 0.09) : 0.4;

    // Get the co-articulation blend targets for the current viseme (if any).
    const blends = VOWEL_BLENDS[viseme] ?? {};

    // Drive every viseme morph target.
    Object.values(VISEMES).forEach((value) => {
      if (value === viseme) {
        // Active viseme: lerp toward volume-scaled intensity.
        lerpMorphTarget(value, intensity, activeLerpSpeed);
      } else if (blends[value] !== undefined) {
        // Adjacent vowel co-articulation: keep a partial shape weighted by
        // both the blend amount and the overall intensity (so it also scales
        // with loudness and fades out on silence).
        lerpMorphTarget(value, blends[value] * intensity, inactiveLerpSpeed);
      } else {
        // All other visemes: decay smoothly to zero.
        lerpMorphTarget(value, 0, inactiveLerpSpeed);
      }
    });
  });

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Hair"
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/64f1a714fe61576b46f27ca2.glb");
useGLTF.preload("/models/animations.glb");
